return {
  -- {
  --   "rcasia/neotest-java",
  --   ft = "java",
  --   dependencies = {
  --     "mfussenegger/nvim-jdtls",
  --     "mfussenegger/nvim-dap", -- for the debugger
  --     "rcarriga/nvim-dap-ui", -- recommended
  --     "theHamsta/nvim-dap-virtual-text", -- recommended
  --   },
  --   keys = {
  --     {
  --       "<leader>tT",
  --       function()
  --         require("neotest").run.run(vim.fn.expand("%"))
  --       end,
  --       mode = "n",
  --       desc = "Run Test File",
  --     },
  --     {
  --       "<leader>tr",
  --       function()
  --         require("neotest").run.run()
  --       end,
  --       mode = "n",
  --       desc = "Run Nearest Test",
  --     },
  --     {
  --       "<leader>tD",
  --       function()
  --         require("neotest").run.run({ strategy = "dap", suite = true })
  --       end,
  --       mode = "n",
  --       desc = "Debug Test File",
  --     },
  --     {
  --       "<leader>td",
  --       function()
  --         require("neotest").run.run({ vim.fn.expand("%"), strategy = "dap", suite = true })
  --       end,
  --       mode = "n",
  --       desc = "Debug Nearest Test",
  --     },
  --   },
  -- },
  -- {
  --   "nvim-neotest/neotest",
  --   dependencies = {
  --     "nvim-neotest/nvim-nio",
  --     "nvim-lua/plenary.nvim",
  --     "antoinemadec/FixCursorHold.nvim",
  --     "nvim-treesitter/nvim-treesitter",
  --   },
  --   opts = {
  --     adapters = {
  --       ["neotest-java"] = {
  --         -- config here
  --       },
  --     },
  --   },
  -- },
}
